# Generated by Django 5.2.4 on 2025-07-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
